#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "> Running pre-commit hooks ...\n"

echo "\n1. build"
rm -rf dist
yarn build

echo "\n2. lint"
yarn lint

echo "\n3. fmt"
yarn fmt

echo "\n4. test"
yarn test

echo "\n\n> DONE!"
